language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=AnnotationControlList
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2.4
  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

  # setup composer requirements
  - if [ -f ../cakephp/.travis.yml ]; then echo '<?php' > core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then echo 'include (ROOT . DS . "vendors" . DS . "autoload.php");' >> core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then echo 'spl_autoload_unregister(["App", "load"]);' >> core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then echo 'spl_autoload_register(["App", "load"], true, true);' >> core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then echo '?>' >> core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then cat ../cakephp/app/Config/core.php >> core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then rm ../cakephp/app/Config/core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then mv core.php ../cakephp/app/Config/core.php; fi
  - if [ -f ../cakephp/.travis.yml ]; then cp Test/test_app/composer.json ../cakephp/composer.json; fi
  - if [ -f ../cakephp/.travis.yml ]; then cd ../cakephp && composer require minime/annotations:2.3.0 && cd -; fi
  - if [ -f ../cakephp/.travis.yml ]; then cd ../cakephp && composer require cakephp/debug_kit:2.2.* && cd -; fi
  - if [ -f ../cakephp/.travis.yml ]; then mv ../cakephp/Plugin/DebugKit ../cakephp/app/Plugin/DebugKit; fi

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
